### ISSUE TITLE
ED2 issues

### ISSUE THREAD

**Issue by Sheigutn** [notdedsec/Jujutsu-Kaisen#1]
The apostrophes are kind of inconsistent, I've spotted both ’ and '.
https://github.com/notdedsec/Jujutsu-Kaisen/blob/ff27eb47d7ee71c5d34322af45d17626d12004d9/common/ED2.ass#L23
https://github.com/notdedsec/Jujutsu-Kaisen/blob/ff27eb47d7ee71c5d34322af45d17626d12004d9/common/ED2.ass#L30

Also, there's a typo in "Tomorrow" twice, here: 
https://github.com/notdedsec/Jujutsu-Kaisen/blob/ff27eb47d7ee71c5d34322af45d17626d12004d9/common/ED2.ass#L33
and here: https://github.com/notdedsec/Jujutsu-Kaisen/blob/ff27eb47d7ee71c5d34322af45d17626d12004d9/common/ED2.ass#L48

**Comment by notdedsec** [comment]
dang, thanks for the heads up. it's been fixed.
